// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIb52Ojn5wSdCSjUimktvOMjaL7ocA-a8',
    appId: '1:843394610359:web:023d83257f844b5aeb0932',
    messagingSenderId: '843394610359',
    projectId: 'habit-quest-1faa3',
    authDomain: 'habit-quest-1faa3.firebaseapp.com',
    storageBucket: 'habit-quest-1faa3.firebasestorage.app',
    measurementId: 'G-YQV5PW3Z96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLPThAXxaOaNMVPk822BGkEvxeAdCByso',
    appId: '1:843394610359:android:642efd3fcf6ba46beb0932',
    messagingSenderId: '843394610359',
    projectId: 'habit-quest-1faa3',
    storageBucket: 'habit-quest-1faa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO6cj10Q5H-HSKB3MGBztYZIICb8_ot8c',
    appId: '1:843394610359:ios:2e513b30b5153b95eb0932',
    messagingSenderId: '843394610359',
    projectId: 'habit-quest-1faa3',
    storageBucket: 'habit-quest-1faa3.firebasestorage.app',
    iosBundleId: 'com.example.habitQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO6cj10Q5H-HSKB3MGBztYZIICb8_ot8c',
    appId: '1:843394610359:ios:2e513b30b5153b95eb0932',
    messagingSenderId: '843394610359',
    projectId: 'habit-quest-1faa3',
    storageBucket: 'habit-quest-1faa3.firebasestorage.app',
    iosBundleId: 'com.example.habitQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIb52Ojn5wSdCSjUimktvOMjaL7ocA-a8',
    appId: '1:843394610359:web:7f853e3705ca647eeb0932',
    messagingSenderId: '843394610359',
    projectId: 'habit-quest-1faa3',
    authDomain: 'habit-quest-1faa3.firebaseapp.com',
    storageBucket: 'habit-quest-1faa3.firebasestorage.app',
    measurementId: 'G-HM44YV8LQE',
  );
}
